CREATE TABLE IF NOT EXISTS t_appartement (
	id INT(11) NOT NULL AUTO_INCREMENT,
	numeroTitre VARCHAR(255) DEFAULT NULL,
	nom VARCHAR(50) DEFAULT NULL,
	superficie DECIMAL(12,2) DEFAULT NULL,
	prix DECIMAL(12,2) DEFAULT NULL,
	niveau VARCHAR(50) DEFAULT NULL,
	facade VARCHAR(50) DEFAULT NULL,
	nombrePiece INT(11) DEFAULT NULL,
	status VARCHAR(50) DEFAULT NULL,
	cave VARCHAR(50) DEFAULT NULL,
	par VARCHAR(50) DEFAULT NULL,
	dateReservation DATE DEFAULT NULL,
	idProjet INT(11) DEFAULT NULL,
	created DATE DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;