CREATE TABLE IF NOT EXISTS t_caisse (
	id INT(11) NOT NULL AUTO_INCREMENT,
	dateOperation DATE DEFAULT NULL,
	personne VARCHAR(100) DEFAULT NULL,
	designation TEXT DEFAULT NULL,
	projet VARCHAR(255) DEFAULT NULL,
	entree DECIMAL(12,2) DEFAULT NULL,
	sortie DECIMAL(12,2) DEFAULT NULL,
	commentaire TEXT DEFAULT NULL,
	created DATE DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;