CREATE TABLE IF NOT EXISTS t_chargescommuns (
	id INT(11) NOT NULL AUTO_INCREMENT,
	dateOperation DATE DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	beneficiaire VARCHAR(100) DEFAULT NULL,
	numeroCheque VARCHAR(50) DEFAULT NULL,
	montant DECIMAL(12,2) DEFAULT NULL,
	idSociete INT(12) DEFAULT NULL,
	idProjet INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;