CREATE TABLE IF NOT EXISTS t_contratEmploye (
	id INT(11) NOT NULL AUTO_INCREMENT,
	dateContrat DATE DEFAULT NULL,
	total DECIMAL(12,2) DEFAULT NULL,
	employe VARCHAR(100) DEFAULT NULL,
	idProjet INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;