CREATE TABLE IF NOT EXISTS t_compteBancaire (
	id INT(11) NOT NULL AUTO_INCREMENT,
	numero VARCHAR(255) DEFAULT NULL,
	idSociete INT(12) DEFAULT NULL,
	dateCreation DATE DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	created DATE DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;