CREATE TABLE IF NOT EXISTS t_employe (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nom VARCHAR(50) DEFAULT NULL,
	cin VARCHAR(50) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	telephone VARCHAR(50) DEFAULT NULL,
	dateCreation DATE DEFAULT NULL,
	created DATE DEFAULT NULL,
	createdBy DATE DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;