CREATE TABLE IF NOT EXISTS t_piecesProjet (
	id INT(11) NOT NULL AUTO_INCREMENT,
	url VARCHAR(255) DEFAULT NULL,
	description TEXT DEFAULT NULL,
	idProjet INT(12) DEFAULT NULL,
	createdBy VARCHAR(100) DEFAULT NULL,
	created DATE DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;