CREATE TABLE IF NOT EXISTS t_projet (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nom VARCHAR(255) DEFAULT NULL,
	numeroTitre TEXT DEFAULT NULL,
	emplacement VARCHAR(255) DEFAULT NULL,
	superficie VARCHAR(50) DEFAULT NULL,
	description TEXT DEFAULT NULL,
	dateCreation DATE DEFAULT NULL,
	createdBy VARCHAR(100) DEFAULT NULL,
	created DATE DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;