CREATE TABLE IF NOT EXISTS t_societe (
	id INT(11) NOT NULL AUTO_INCREMENT,
	raisonSociale TEXT DEFAULT NULL,
	dateCreation DATE DEFAULT NULL,
	createdBy VARCHAR(100) DEFAULT NULL,
	created DATE DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;